# NUMPY TO THE RESCUE

Welcome to the NumPy tutorial. I am super excited that you're here and I sincerely hope you have enjoyed the course thus far. We will heavily use the slicing notation and basic python concepts in this section. If you have not completed the previous tutorials, I strongly suggest you run through them before you proceed.

- Python Basics
- Object Oriented Python
- Python for Data Science
- **NumPy**
- Pandas
- Plotting 
    - Matplotlib
    - Seaborn
    - Plotly
    
Let's get coding !!

### NUMPY ARRAYS
We have two types of NumPy arrays. 
- Vectors
- Matrices

Vectors are one dimensional arrays where as Matrices are two dimensional. 

In [1]:
l = [1,2,3,4,5]
import numpy as np
# np is an alias for our ease
arr = np.array(l)
arr

array([1, 2, 3, 4, 5])

In [2]:
m = [[1,2,3],
     [4,5,6],
     [7,8,9]]
np.array(m)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [4]:
np.arange(0,51,5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [5]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [6]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
np.ones(12)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [9]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
np.random.rand(3)

array([0.37988272, 0.4942286 , 0.43237454])

In [11]:
np.random.randn(3)

array([ 1.47981765,  1.06945115, -2.28809013])

In [12]:
np.random.randint(1,100,5)#1-100 range

array([38, 40, 93, 99, 32])

In [13]:
arr = np.random.randint(1,100,(3,4))
arr

array([[59, 67, 75, 43],
       [28, 68, 40, 53],
       [43, 67, 90, 88]])

In [14]:
arr.reshape(4,3)

array([[59, 67, 75],
       [43, 28, 68],
       [40, 53, 43],
       [67, 90, 88]])

In [15]:
arr.reshape(-1,1)

array([[59],
       [67],
       [75],
       [43],
       [28],
       [68],
       [40],
       [53],
       [43],
       [67],
       [90],
       [88]])

In [16]:
arr.reshape(1,-1)

array([[59, 67, 75, 43, 28, 68, 40, 53, 43, 67, 90, 88]])

In [17]:
arr.max()

90

In [18]:
arr.min()

28

In [19]:
arr.argmin()

4

In [20]:
arr.argmax()

10

In [21]:
len(arr)

3

### INDEXING, SLICING AND SELECTION IN NUMPY

In [22]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
arr[1:4]

array([1, 2, 3])

In [24]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [25]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [26]:
arr[0:5] = 0
arr

array([ 0,  0,  0,  0,  0,  5,  6,  7,  8,  9, 10])

In [27]:
#Slicing is exactly what it sounds like
#Changing a slice means changing the entire array
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
_slice = arr[2:5]
_slice

array([2, 3, 4])

In [29]:
_slice[:] = 200
arr

array([  0,   1, 200, 200, 200,   5,   6,   7,   8,   9,  10])

In [30]:
#Hence it is advised that you create copies.
arr_copy = arr.copy()
arr_copy

array([  0,   1, 200, 200, 200,   5,   6,   7,   8,   9,  10])

In [31]:
_2d = np.random.randint(1,1000,(3,3))
_2d

array([[154, 807, 573],
       [ 41, 212,   7],
       [863, 502,  74]])

In [32]:
_2d[1][2]

7

In [33]:
_2d[1,2]

7

In [34]:
_2d[:2,1:]

array([[807, 573],
       [212,   7]])

In [35]:
_2d[:2]

array([[154, 807, 573],
       [ 41, 212,   7]])

In [36]:
bool_2d = _2d<500
bool_2d

array([[ True, False, False],
       [ True,  True,  True],
       [False, False,  True]])

In [37]:
_2d[bool_2d]

array([154,  41, 212,   7,  74])

In [38]:
_2d[_2d<500]

array([154,  41, 212,   7,  74])

### OPERATIONS ON NUMPY ARRAYS

In [39]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [41]:
arr+100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [42]:
arr/arr

C:\Anaconda\envs\py35\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [43]:
arr**3

array([   0,    1,    8,   27,   64,  125,  216,  343,  512,  729, 1000],
      dtype=int32)

In [44]:
np.max(arr)

10

In [45]:
_2d = np.arange(9).reshape(3,3)
_2d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [46]:
_2d.sum(axis=1)

array([ 3, 12, 21])

In [47]:
_2d.sum(axis=0)

array([ 9, 12, 15])

### WELCOME TO THE END OF THE TUTORIAL
You made it!! Hope you enjoyed taking this tutorial as much as I enjoyed coding it. From the next tutorial, we will be starting data manipulations in Pandas. Until then, happy coding. 

---------------------------------------------------------------------------------
Copyrights © 2018, All Rights Reserved.
- Author: Mahnoor Anjum.
- Course: The Complete Hands-On Machine Learning Course
- Date Created: 2018-06-27
- Date Modified: -